name: Publish Package
on:
  release:
    types: [published]
jobs:
  test:
    uses: ./.github/workflows/test.yml
  release:
    name: Publish package
    needs: [ test ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: https://registry.npmjs.org
          always-auth: true
          scope: '@snnrk'
      - name: Install packages
        run: npm clean-install --include=dev
      - name: Check Tag
        id: check-tag
        run: |
          if [[ ${{ github.ref }} =~ ^refs/tags/@snnrk/localfs@ ]]; then
            echo "package=localfs" >> $GITHUB_OUTPUT
          elif [[ ${{ github.ref }} =~ ^refs/tags/@snnrk/gridfs@ ]]; then
            echo "package=gridfs" >> $GITHUB_OUTPUT
          else
            echo "Invalid tag format" && exit 1
          fi
      - name: Publish Package
        if: steps.check-tag.outputs.package != ''
        run: npm publish -w packages/${{ steps.check-tag.outputs.package }} --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_ENV: production
