name: Publish Package
on:
  release:
    types: [published]
jobs:
  test:
    uses: ./.github/workflows/test.yml
  release:
    name: Publish package
    needs: [ test ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: https://registry.npmjs.org
          always-auth: true
          scope: '@snnrk'
      - name: Install packages
        run: npm clean-install --include=dev
      - name: Publish packages/localfs
        run: npm publish -w packages/localfs publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_ENV: production
